import { MEMORIES_KEY } from '../constants.js';
import { getDeps } from '../deps.js';
import { getOpenVaultData } from '../store/chat-data.js';
import { deleteEmbedding, hasEmbedding } from '../utils/embedding-codec.js';
import { logDebug, logInfo } from '../utils/logging.js';

/**
 * Count total embeddings across memories, graph nodes, and communities.
 * @param {Object} data - OpenVault chat data
 * @returns {number}
 */
function _countEmbeddings(data) {
    let count = 0;
    for (const m of data[MEMORIES_KEY] || []) {
        if (hasEmbedding(m)) count++;
    }
    for (const node of Object.values(data.graph?.nodes || {})) {
        if (hasEmbedding(node)) count++;
    }
    for (const edge of Object.values(data.graph?.edges || {})) {
        if (hasEmbedding(edge)) count++;
    }
    for (const community of Object.values(data.communities || {})) {
        if (hasEmbedding(community)) count++;
    }
    return count;
}

/**
 * Check if stored embeddings were generated by a different model.
 * If mismatch detected, wipe all embeddings and update the model tag.
 *
 * @param {Object} data - OpenVault chat data (chatMetadata.openvault)
 * @param {string} currentModelId - Currently selected embedding source
 * @returns {Promise<number>} Number of embeddings wiped (0 = no mismatch)
 */
export async function invalidateStaleEmbeddings(data, currentModelId) {
    if (!data || !currentModelId) return 0;

    const hasAnyEmbedding = _countEmbeddings(data) > 0;

    // No tag yet
    if (!data.embedding_model_id) {
        if (!hasAnyEmbedding) {
            // Brand new chat — just stamp
            data.embedding_model_id = currentModelId;
            return 0;
        }
        // Legacy chat with embeddings but no tag → fall through to wipe
    }

    // Same model — no action needed
    if (data.embedding_model_id === currentModelId) {
        return 0;
    }

    // MISMATCH — wipe everything
    const oldModel = data.embedding_model_id || 'unknown';
    let count = 0;

    for (const m of data[MEMORIES_KEY] || []) {
        if (hasEmbedding(m)) {
            deleteEmbedding(m);
            count++;
        }
    }

    for (const node of Object.values(data.graph?.nodes || {})) {
        if (hasEmbedding(node)) {
            deleteEmbedding(node);
            count++;
        }
    }

    for (const edge of Object.values(data.graph?.edges || {})) {
        if (hasEmbedding(edge)) {
            deleteEmbedding(edge);
            count++;
        }
    }

    for (const community of Object.values(data.communities || {})) {
        if (hasEmbedding(community)) {
            deleteEmbedding(community);
            count++;
        }
    }

    data.embedding_model_id = currentModelId;
    logInfo(`Embedding model changed (${oldModel} → ${currentModelId}). Wiped ${count} embeddings.`);
    return count;
}

/**
 * Delete embeddings from current chat's memories
 * @returns {Promise<number>} Number of embeddings deleted
 */
export async function deleteCurrentChatEmbeddings() {
    const data = getOpenVaultData();
    if (!data || !data[MEMORIES_KEY]) {
        return 0;
    }

    let count = 0;
    for (const memory of data[MEMORIES_KEY]) {
        if (hasEmbedding(memory)) {
            deleteEmbedding(memory);
            count++;
        }
    }

    if (count > 0) {
        await getDeps().saveChatConditional();
        logDebug(`Deleted ${count} embeddings`);
    }

    return count;
}
