import { MEMORIES_KEY } from '../constants.js';
import { getDeps } from '../deps.js';
import { getSTVectorRequestBody, getSTVectorSource, purgeSTCollection } from '../services/st-vector.js';
import { getCurrentChatId, getOpenVaultData } from '../store/chat-data.js';
import { clearStSynced, deleteEmbedding, hasEmbedding, isStSynced } from '../utils/embedding-codec.js';
import { logDebug, logInfo, logWarn } from '../utils/logging.js';

/**
 * Get the current ST Vector Storage fingerprint (source + model) from ST settings.
 * Used to detect when the user changes vectorization settings on the ST side.
 * @returns {{source: string, model: string}} Current ST vector source and model
 */
export function getStVectorFingerprint() {
    const source = getSTVectorSource();
    const body = getSTVectorRequestBody(source);
    return { source, model: body.model || '' };
}

/**
 * Stamp ST Vector Storage fingerprint onto chat data after successful sync.
 * Call this after inserting items into ST so mismatch detection works on next load.
 * @param {Object} data - OpenVault chat data (chatMetadata.openvault)
 */
export function stampStVectorFingerprint(data) {
    if (!data) return;
    const fp = getStVectorFingerprint();
    data.st_vector_source = fp.source;
    data.st_vector_model = fp.model;
}

/**
 * Check if the ST Vector fingerprint (source + model) has changed.
 * @param {Object} data - OpenVault chat data
 * @returns {boolean} True if ST-side settings changed since last sync
 */
function _hasStVectorMismatch(data) {
    // No fingerprint stored yet — not a mismatch (first sync will stamp it)
    if (!data.st_vector_source && !data.st_vector_model) {
        // But if items are already synced, treat as mismatch (legacy data)
        const hasSynced = _hasSyncedItems(data);
        return hasSynced;
    }
    const fp = getStVectorFingerprint();
    return data.st_vector_source !== fp.source || data.st_vector_model !== fp.model;
}

/**
 * Check if any items have the _st_synced flag.
 * @param {Object} data - OpenVault chat data
 * @returns {boolean}
 */
function _hasSyncedItems(data) {
    for (const m of data[MEMORIES_KEY] || []) {
        if (isStSynced(m)) return true;
    }
    for (const node of Object.values(data.graph?.nodes || {})) {
        if (isStSynced(node)) return true;
    }
    for (const community of Object.values(data.communities || {})) {
        if (isStSynced(community)) return true;
    }
    return false;
}

/**
 * Clear all ST sync flags and fingerprint from data.
 * @param {Object} data - OpenVault chat data
 * @returns {number} Number of sync flags cleared
 */
function _clearAllStSyncFlags(data) {
    let count = 0;
    for (const m of data[MEMORIES_KEY] || []) {
        if (isStSynced(m)) {
            clearStSynced(m);
            count++;
        }
    }
    for (const node of Object.values(data.graph?.nodes || {})) {
        if (isStSynced(node)) {
            clearStSynced(node);
            count++;
        }
    }
    for (const community of Object.values(data.communities || {})) {
        if (isStSynced(community)) {
            clearStSynced(community);
            count++;
        }
    }
    delete data.st_vector_source;
    delete data.st_vector_model;
    return count;
}

/**
 * Count total embeddings across memories, graph nodes, and communities.
 * @param {Object} data - OpenVault chat data
 * @returns {number}
 */
function _countEmbeddings(data) {
    let count = 0;
    for (const m of data[MEMORIES_KEY] || []) {
        if (hasEmbedding(m)) count++;
    }
    for (const node of Object.values(data.graph?.nodes || {})) {
        if (hasEmbedding(node)) count++;
    }
    for (const community of Object.values(data.communities || {})) {
        if (hasEmbedding(community)) count++;
    }
    return count;
}

/**
 * Check if stored embeddings were generated by a different model.
 * If mismatch detected, wipe all embeddings and update the model tag.
 * For ST Vector Storage, also detects source/model changes on the ST side.
 *
 * @param {Object} data - OpenVault chat data (chatMetadata.openvault)
 * @param {string} currentModelId - Currently selected embedding source
 * @returns {Promise<number>} Number of embeddings/sync-flags wiped (0 = no mismatch)
 */
export async function invalidateStaleEmbeddings(data, currentModelId) {
    if (!data || !currentModelId) return 0;

    const hasAnyEmbedding = _countEmbeddings(data) > 0;

    // No tag yet
    if (!data.embedding_model_id) {
        if (!hasAnyEmbedding) {
            // Brand new chat — just stamp
            data.embedding_model_id = currentModelId;
            if (currentModelId === 'st_vector') {
                stampStVectorFingerprint(data);
            }
            return 0;
        }
        // Legacy chat with embeddings but no tag → fall through to wipe
    }

    // Same OV source — but if ST Vector, also check ST-side fingerprint
    if (data.embedding_model_id === currentModelId) {
        if (currentModelId === 'st_vector' && _hasStVectorMismatch(data)) {
            // ST source/model changed — purge old collection, clear sync flags, re-sync
            const oldSource = data.st_vector_source || 'unknown';
            const oldModel = data.st_vector_model || 'unknown';
            const fp = getStVectorFingerprint();

            const cleared = _clearAllStSyncFlags(data);

            // Purge old ST collection (best-effort, don't block on failure)
            try {
                await purgeSTCollection(getCurrentChatId() || 'default');
            } catch (e) {
                logWarn(`Failed to purge old ST collection: ${e.message}`);
            }

            // Stamp new fingerprint
            stampStVectorFingerprint(data);

            logInfo(
                `ST vector source changed (${oldSource}/${oldModel} → ${fp.source}/${fp.model}). Cleared ${cleared} sync flags.`
            );
            return cleared;
        }
        return 0;
    }

    // MISMATCH — wipe everything
    const oldModel = data.embedding_model_id || 'unknown';
    let count = 0;

    for (const m of data[MEMORIES_KEY] || []) {
        if (hasEmbedding(m)) {
            deleteEmbedding(m);
            count++;
        }
    }

    for (const node of Object.values(data.graph?.nodes || {})) {
        if (hasEmbedding(node)) {
            deleteEmbedding(node);
            count++;
        }
    }

    for (const community of Object.values(data.communities || {})) {
        if (hasEmbedding(community)) {
            deleteEmbedding(community);
            count++;
        }
    }

    // Also clear ST sync flags
    const syncCleared = _clearAllStSyncFlags(data);
    count += syncCleared;

    // Purge old ST collection if switching away from st_vector
    if (oldModel === 'st_vector') {
        try {
            await purgeSTCollection(getCurrentChatId() || 'default');
        } catch (e) {
            logWarn(`Failed to purge old ST collection: ${e.message}`);
        }
    }

    data.embedding_model_id = currentModelId;
    if (currentModelId === 'st_vector') {
        stampStVectorFingerprint(data);
    }

    logInfo(`Embedding model changed (${oldModel} → ${currentModelId}). Wiped ${count} embeddings.`);
    return count;
}

/**
 * Delete embeddings from current chat's memories
 * @returns {Promise<number>} Number of embeddings deleted
 */
export async function deleteCurrentChatEmbeddings() {
    const data = getOpenVaultData();
    if (!data || !data[MEMORIES_KEY]) {
        return 0;
    }

    let count = 0;
    for (const memory of data[MEMORIES_KEY]) {
        if (hasEmbedding(memory)) {
            deleteEmbedding(memory);
            count++;
        }
    }

    if (count > 0) {
        await getDeps().saveChatConditional();
        logDebug(`Deleted ${count} embeddings`);
    }

    return count;
}
