import { CHARACTERS_KEY, LAST_PROCESSED_KEY, MEMORIES_KEY, METADATA_KEY } from '../constants.js';
import { getDeps } from '../deps.js';
import { record } from '../perf/store.js';
import { showToast } from './dom.js';
import { deleteEmbedding, hasEmbedding } from './embedding-codec.js';
import { logDebug, logError, logWarn } from './logging.js';

/**
 * Get OpenVault data from chat metadata
 * @returns {Object|null} Returns null if context is not available
 */
export function getOpenVaultData() {
    const context = getDeps().getContext();
    if (!context) {
        logWarn('getContext() returned null/undefined');
        return null;
    }
    if (!context.chatMetadata) {
        context.chatMetadata = {};
    }
    if (!context.chatMetadata[METADATA_KEY]) {
        context.chatMetadata[METADATA_KEY] = {
            [MEMORIES_KEY]: [],
            [CHARACTERS_KEY]: {},
            [LAST_PROCESSED_KEY]: -1,
        };
    }
    const data = context.chatMetadata[METADATA_KEY];

    return data;
}

/**
 * Get current chat ID for tracking across async operations
 * @returns {string|null}
 */
export function getCurrentChatId() {
    const context = getDeps().getContext();
    return context?.chatId || context?.chat_metadata?.chat_id || null;
}

/**
 * Save OpenVault data to chat metadata
 * @param {string} [expectedChatId] - If provided, verify chat hasn't changed before saving
 * @returns {Promise<boolean>} True if save succeeded, false otherwise
 */
export async function saveOpenVaultData(expectedChatId = null) {
    const t0 = performance.now();
    if (expectedChatId !== null) {
        const currentId = getCurrentChatId();
        if (currentId !== expectedChatId) {
            logWarn(
                `Chat changed during operation (expected: ${expectedChatId}, current: ${currentId}), aborting save`
            );
            return false;
        }
    }

    try {
        await getDeps().saveChatConditional();
        record('chat_save', performance.now() - t0);
        logDebug('Data saved to chat metadata');
        return true;
    } catch (error) {
        record('chat_save', performance.now() - t0);
        logError('Failed to save data', error);
        showToast('error', `Failed to save data: ${error.message}`);
        return false;
    }
}

/**
 * Generate a unique ID
 * @returns {string}
 */
export function generateId() {
    return `${getDeps().Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
}

/**
 * Update a memory by ID
 * @param {string} id - Memory ID to update
 * @param {Object} updates - Fields to update (summary, importance, tags, is_secret)
 * @returns {Promise<boolean>} True if updated, false otherwise
 */
export async function updateMemory(id, updates) {
    const data = getOpenVaultData();
    if (!data) {
        showToast('warning', 'No chat loaded');
        return false;
    }

    const memory = data[MEMORIES_KEY]?.find((m) => m.id === id);
    if (!memory) {
        logDebug(`Memory ${id} not found`);
        return false;
    }

    // Track if summary changed (requires re-embedding)
    const summaryChanged = updates.summary !== undefined && updates.summary !== memory.summary;

    // Apply allowed updates
    const allowedFields = ['summary', 'importance', 'tags', 'is_secret'];
    for (const field of allowedFields) {
        if (updates[field] !== undefined) {
            memory[field] = updates[field];
        }
    }

    // If summary changed, invalidate embedding so it can be regenerated
    if (summaryChanged) {
        deleteEmbedding(memory);
    }

    await getDeps().saveChatConditional();
    logDebug(`Updated memory ${id}${summaryChanged ? ' (embedding invalidated)' : ''}`);
    return true;
}

/**
 * Delete a memory by ID
 * @param {string} id - Memory ID to delete
 * @returns {Promise<boolean>} True if deleted, false otherwise
 */
export async function deleteMemory(id) {
    const data = getOpenVaultData();
    if (!data) {
        showToast('warning', 'No chat loaded');
        return false;
    }

    const idx = data[MEMORIES_KEY]?.findIndex((m) => m.id === id);
    if (idx === -1) {
        logDebug(`Memory ${id} not found`);
        return false;
    }

    data[MEMORIES_KEY].splice(idx, 1);
    await getDeps().saveChatConditional();
    logDebug(`Deleted memory ${id}`);
    return true;
}

/**
 * Delete all OpenVault data for the current chat
 * @returns {Promise<boolean>} True if deleted, false otherwise
 */
export async function deleteCurrentChatData() {
    const context = getDeps().getContext();

    if (!context.chatMetadata) {
        logDebug('No chat metadata found');
        return false;
    }

    delete context.chatMetadata[METADATA_KEY];
    await getDeps().saveChatConditional();
    logDebug('Deleted all chat data');
    return true;
}

/**
 * Check if stored embeddings were generated by a different model.
 * If mismatch detected, wipe all embeddings and update the model tag.
 *
 * @param {Object} data - OpenVault chat data (chatMetadata.openvault)
 * @param {string} currentModelId - Currently selected embedding source
 * @returns {number} Number of embeddings wiped (0 = no mismatch)
 */
export function invalidateStaleEmbeddings(data, currentModelId) {
    if (!data || !currentModelId) return 0;

    const hasAnyEmbedding = _countEmbeddings(data) > 0;

    // No tag yet
    if (!data.embedding_model_id) {
        if (!hasAnyEmbedding) {
            // Brand new chat — just stamp
            data.embedding_model_id = currentModelId;
            return 0;
        }
        // Legacy chat with embeddings but no tag → fall through to wipe
    }

    // Match → no-op
    if (data.embedding_model_id === currentModelId) {
        return 0;
    }

    // MISMATCH — wipe everything
    const oldModel = data.embedding_model_id || 'unknown';
    let count = 0;

    for (const m of data[MEMORIES_KEY] || []) {
        if (hasEmbedding(m)) {
            deleteEmbedding(m);
            count++;
        }
    }

    for (const node of Object.values(data.graph?.nodes || {})) {
        if (hasEmbedding(node)) {
            deleteEmbedding(node);
            count++;
        }
    }

    for (const community of Object.values(data.communities || {})) {
        if (hasEmbedding(community)) {
            deleteEmbedding(community);
            count++;
        }
    }

    data.embedding_model_id = currentModelId;
    logDebug(`Embedding model changed (${oldModel} → ${currentModelId}). Wiped ${count} embeddings.`);
    return count;
}

/**
 * Count total embeddings across memories, graph nodes, and communities.
 * @param {Object} data - OpenVault chat data
 * @returns {number}
 */
function _countEmbeddings(data) {
    let count = 0;
    for (const m of data[MEMORIES_KEY] || []) {
        if (hasEmbedding(m)) count++;
    }
    for (const node of Object.values(data.graph?.nodes || {})) {
        if (hasEmbedding(node)) count++;
    }
    for (const community of Object.values(data.communities || {})) {
        if (hasEmbedding(community)) count++;
    }
    return count;
}

/**
 * Delete embeddings from current chat's memories
 * @returns {Promise<number>} Number of embeddings deleted
 */
export async function deleteCurrentChatEmbeddings() {
    const data = getOpenVaultData();
    if (!data || !data[MEMORIES_KEY]) {
        return 0;
    }

    let count = 0;
    for (const memory of data[MEMORIES_KEY]) {
        if (hasEmbedding(memory)) {
            deleteEmbedding(memory);
            count++;
        }
    }

    if (count > 0) {
        await getDeps().saveChatConditional();
        logDebug(`Deleted ${count} embeddings`);
    }

    return count;
}
